# Module metadata for the test harness.
# Each entry: (number, slug, title, species, tier, age_band, cbe_strand)
MODULES = [
    # Term 1: Ocean Foundations
    (1, "meet-the-mako-coder", "Meet the Mako Coder", "Shortfin mako shark", "Tide Pool", "12-15", "Digital Literacy"),
    (2, "turtle-beach-sequencing", "Turtle Beach — Sequencing", "Green sea turtle", "Tide Pool", "12-15", "Algorithms"),
    (3, "hatchling-dash", "Hatchling Dash — Sprites & Motion", "Green sea turtle", "Tide Pool", "12-15", "Algorithms"),
    (4, "dolphin-loops", "Dolphin Loops", "Spinner dolphin", "Tide Pool", "12-15", "Algorithms"),
    (5, "coral-patterns", "Coral Patterns — Nested Loops", "Hawksbill sea turtle", "Tide Pool", "12-15", "Algorithms"),
    (6, "humpback-dolphin-conditional", "If It's a Humpback Dolphin…", "Indian Ocean humpback dolphin", "Tide Pool", "12-15", "Algorithms"),
    (7, "reef-branching", "Reef Branching — If-Else Ladders", "Coral reefs", "Tide Pool", "12-15", "Algorithms"),
    (8, "whale-shark-variables", "Whale Shark Filter — Variables", "Whale shark", "Tide Pool", "12-15", "Algorithms"),
    (9, "pod-click-events", "Pod Click — Events", "Spinner dolphin", "Tide Pool", "12-15", "Algorithms"),
    (10, "debug-the-mangrove", "Debug the Mangrove", "Mangroves", "Tide Pool", "12-15", "Critical Thinking"),
    (11, "decompose-turtle-rescue", "Decompose a Turtle Rescue", "Green sea turtle", "Tide Pool", "12-15", "Algorithms"),
    (12, "ocean-scene-sprint", "Ocean Scene Sprint", "Mixed marine life", "Tide Pool", "12-15", "Creativity"),
    (13, "term-1-showcase", "Term 1 Showcase & Reflection", "Mixed marine life", "Tide Pool", "12-15", "Learning to Learn"),
    # Term 2: Data & Coastal Systems
    (14, "blocks-to-text", "From Blocks to Text", "Shortfin mako shark", "Coral Reef", "12-15", "Digital Literacy"),
    (15, "data-types-deep", "Data Types of the Deep", "Whale shark", "Coral Reef", "12-15", "Data"),
    (16, "lists-kenyan-marine-life", "Lists of Kenyan Marine Life", "All species", "Coral Reef", "12-15", "Data"),
    (17, "filtering-plankton", "Filtering the Plankton", "Whale shark", "Coral Reef", "12-15", "Data"),
    (18, "seagrass-coordinates", "Seagrass Coordinates", "Seagrass beds", "Coral Reef", "12-15", "Data"),
    (19, "dictionary-dugong", "Dictionary of the Dugong", "Dugong", "Coral Reef", "12-15", "Data"),
    (20, "functions-fish-schools", "Functions for Fish Schools", "Mixed fish", "Coral Reef", "12-15", "Algorithms"),
    (21, "turtle-nesting-timer", "Turtle Nesting Timer", "Green sea turtle", "Coral Reef", "12-15", "Data"),
    (22, "survey-data-2023", "Survey Data — 2023 Aerial Count", "All megafauna", "Coral Reef", "12-15", "Data"),
    (23, "plot-the-coast", "Plot the Coast", "Survey results", "Coral Reef", "12-15", "Data"),
    (24, "whale-song-arrays", "Whale Song Arrays", "Humpback whale", "Coral Reef", "12-15", "Data"),
    (25, "data-ethics-wildlife", "Data Ethics — Keep Wildlife Safe", "All species", "Coral Reef", "12-15", "Citizenship"),
    (26, "marine-data-explorer", "Marine Data Explorer Mini-Project", "Mixed marine life", "Coral Reef", "12-15", "Data"),
    # Term 3: Hardware & Networks
    (27, "inputs-from-ocean", "Inputs from the Ocean", "Mangroves", "Open Ocean", "12-15", "Computers"),
    (28, "temperature-watch", "Temperature Watch", "Coral reefs", "Open Ocean", "12-15", "Computers"),
    (29, "tide-guard-light", "Tide-guard Light", "Seagrass beds", "Open Ocean", "12-15", "Computers"),
    (30, "compass-dolphin", "Compass Dolphin", "Spinner dolphin", "Open Ocean", "12-15", "Computers"),
    (31, "radio-tag-mako", "Radio Tag — micro:bit Networks", "Shortfin mako shark", "Open Ocean", "12-15", "Networks"),
    (32, "simulated-shark-tracker", "Simulated Shark Tracker", "Shortfin mako shark", "Open Ocean", "12-15", "Networks"),
    (33, "internet-and-ocean", "Internet and the Ocean", "All species", "Open Ocean", "12-15", "Networks"),
    (34, "apis-ocean-facts", "APIs — Fetching Ocean Facts", "Whale shark", "Open Ocean", "12-15", "Networks"),
    (35, "automate-tide-log", "Automate the Tide Log", "Seagrass beds", "Open Ocean", "12-15", "Algorithms"),
    (36, "physical-computing-showcase", "Physical Computing Showcase", "Mixed marine life", "Open Ocean", "12-15", "Creativity"),
    (37, "cybersecurity-at-sea", "Cybersecurity at Sea", "All species", "Open Ocean", "12-15", "Security"),
    (38, "digital-citizenship-clean-coasts", "Digital Citizenship — Clean Coasts", "Mangroves", "Open Ocean", "12-15", "Citizenship"),
    (39, "term-3-showcase", "Term 3 Showcase & Reflection", "Mixed marine life", "Open Ocean", "12-15", "Learning to Learn"),
    # Term 4: Conservation & Capstone
    (40, "planning-mako-expedition", "Planning the Mako Shark Expedition", "Shortfin mako shark", "Mako Hunter", "15-18", "Project"),
    (41, "functions-hunt-mode", "Functions Revisited — Hunt Mode", "Shortfin mako shark", "Mako Hunter", "15-18", "Algorithms"),
    (42, "classes-coral-reef", "Classes of the Coral Reef", "Coral reefs", "Mako Hunter", "15-18", "Algorithms"),
    (43, "data-driven-decisions", "Data-Driven Decisions", "All species", "Mako Hunter", "15-18", "Data"),
    (44, "events-game-loop", "Events and the Game Loop", "Shortfin mako shark", "Mako Hunter", "15-18", "Algorithms"),
    (45, "capstone-world-species", "Capstone Build 1 — World & Species", "Mixed marine life", "Mako Hunter", "15-18", "Project"),
    (46, "capstone-interactions", "Capstone Build 2 — Interactions", "Shortfin mako shark", "Mako Hunter", "15-18", "Project"),
    (47, "capstone-data-conservation", "Capstone Build 3 — Data & Conservation", "All species", "Mako Hunter", "15-18", "Project"),
    (48, "capstone-polish-evaluate", "Capstone Build 4 — Polish & Evaluate", "All species", "Mako Hunter", "15-18", "Project"),
    (49, "ui-accessibility", "User Interface and Accessibility", "All species", "Mako Hunter", "15-18", "Digital Literacy"),
    (50, "peer-review-beta", "Peer Review and Beta Test", "All species", "Mako Hunter", "15-18", "Communication"),
    (51, "final-presentation-rehearsal", "Final Presentation Rehearsal", "All species", "Mako Hunter", "15-18", "Communication"),
    (52, "mako-shark-expedition-showcase", "Mako Shark Expedition Showcase", "All species", "Mako Hunter", "15-18", "Citizenship"),
]
